{% set name = "eeyore" %}
{% set version = "0.0.20" %}
{% set python_min = "3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0597b1dc516bdf73e6ae6096f7c41d41bda6e514bac115abe485f35aad3d4b60

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - kanga >=0.0.20
    - numpy >=1.19.2
    - python >={{ python_min }}
    - pytorch-cpu

test:
  imports:
    - eeyore
  requires:
    - python {{ python_min }}

about:
  home: "https://github.com/papamarkou/eeyore"
  license: MIT
  license_file: LICENSE.txt
  summary: "MCMC methods for neural networks"

extra:
  recipe-maintainers:
    - papamarkou
